# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'blazr' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
   use_frameworks!

  # Pods for blazr
  pod 'RMQClient', :git => 'https://github.com/rabbitmq/rabbitmq-objc-client.git'

  target 'blazrTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'blazr-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for blazr-tvOS

  target 'blazr-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
